tipo = input('Digite para saber o tipo primitivo: ')
print('O tipo é', type(tipo))
print('Só tem espaços?', tipo.isspace())
print('É um número?', tipo.isnumeric())
print('É alfabético?', tipo.isalpha())
print('É alfanúmerico', tipo.isalnum())
print('Esta em maiúsculas?', tipo.isupper())
print('Esta em minúsculas?', tipo.lower())
print('Esta capitalizda?', tipo.istitle())
